### ISSUE TITLE
SVG images on non-Edge IE are 150px in height

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/wagtail-svgmap#7]
Apparently, responsive SVGs require an IE-specific hack:

``` css
.container {
    height: 0;             /* collapse the container's height */
    width: width-value;    /* specify any width you want (a percentage value, basically) */
    /* apply a padding using the following formula */
    /* this formula makes sure the aspect ratio of the container equals that of the svg graphic */
    padding-top: (svg height / svg width) * width-value;
    position: relative;    /* create positioning context for svg */
}

svg {
    position: absolute;
    top: 0;
    left: 0;
}
```

(source: http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/)
